/**
 * VANILLA JAVASCRIPT SECURITY SIDEBAR
 * 
 * This is a standalone implementation without React dependencies.
 * Use this if you prefer vanilla JS or need to integrate with a different framework.
 * 
 * Include: <script src="security-sidebar.js"></script>
 * Initialize: SecuritySidebar.init({ callbacks object });
 */

class SecuritySidebar {
  constructor(options = {}) {
    this.options = {
      containerId: options.containerId || 'app',
      onScan: options.onScan || (() => {}),
      onNavigate: options.onNavigate || (() => {}),
      onUpgrade: options.onUpgrade || (() => {}),
      ...options,
    };

    this.state = {
      urlInput: '',
      activeSection: 'url-scanner',
      isMobileOpen: false,
    };

    this.elements = {};
    this.init();
  }

  init() {
    this.createMarkup();
    this.cacheElements();
    this.attachEventListeners();
  }

  createMarkup() {
    const container = document.getElementById(this.options.containerId);
    
    const sidebarHTML = `
      <button class="sidebar-mobile-toggle" aria-label="Toggle sidebar">
        <svg class="menu-icon" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <line x1="3" y1="6" x2="21" y2="6"></line>
          <line x1="3" y1="12" x2="21" y2="12"></line>
          <line x1="3" y1="18" x2="21" y2="18"></line>
        </svg>
        <svg class="close-icon" style="display: none;" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <line x1="18" y1="6" x2="6" y2="18"></line>
          <line x1="6" y1="6" x2="18" y2="18"></line>
        </svg>
      </button>

      <div class="sidebar-overlay" style="display: none;"></div>

      <aside class="security-sidebar">
        <!-- URL Scanner Section -->
        <div class="sidebar-section url-scanner-card">
          <div class="url-scanner-header">
            <h2 class="section-title">URL Scanner</h2>
            <span class="free-badge">FREE</span>
          </div>

          <div class="url-input-wrapper">
            <input
              type="url"
              class="url-input"
              id="urlInput"
              placeholder="https://example.com"
              aria-label="Enter URL to scan"
            />
          </div>

          <button class="scan-button" id="scanBtn" aria-label="Scan URL">
            <svg class="button-icon" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"></polygon>
            </svg>
            <span>SCAN</span>
          </button>
        </div>

        <!-- Scan Capabilities Section -->
        <div class="sidebar-section capabilities-section">
          <h3 class="section-label">SCAN CAPABILITIES</h3>

          <ul class="capabilities-list" id="capabilitiesList">
            <!-- Items generated by JS -->
          </ul>
        </div>

        <!-- Quick Actions Section -->
        <div class="sidebar-section quick-actions-section">
          <h3 class="section-label">QUICK ACTIONS</h3>

          <div class="quick-actions-grid" id="quickActionsGrid">
            <!-- Items generated by JS -->
          </div>
        </div>

        <!-- Upgrade / Pro Section -->
        <div class="sidebar-section upgrade-card">
          <div class="upgrade-header">
            <svg class="crown-icon" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <path d="M6 9l6-6 6 6M3 9h18M4 13h5l2 5h2l2-5h5M10 15l-1 5h6l-1-5"></path>
            </svg>
            <h3 class="upgrade-title">Unlock Pro Features</h3>
          </div>

          <p class="upgrade-description">
            PDF Reports • Bulk Scanning • API Access • Priority Support
          </p>

          <button class="upgrade-button" id="upgradeBtn" aria-label="Upgrade to Pro">
            Upgrade Now
          </button>
        </div>
      </aside>
    `;

    container.insertAdjacentHTML('afterbegin', sidebarHTML);
  }

  cacheElements() {
    this.elements = {
      sidebar: document.querySelector('.security-sidebar'),
      mobileToggle: document.querySelector('.sidebar-mobile-toggle'),
      overlay: document.querySelector('.sidebar-overlay'),
      menuIcon: document.querySelector('.menu-icon'),
      closeIcon: document.querySelector('.close-icon'),
      urlInput: document.getElementById('urlInput'),
      scanBtn: document.getElementById('scanBtn'),
      upgradeBtn: document.getElementById('upgradeBtn'),
      capabilitiesList: document.getElementById('capabilitiesList'),
      quickActionsGrid: document.getElementById('quickActionsGrid'),
    };
  }

  attachEventListeners() {
    // Mobile toggle
    this.elements.mobileToggle.addEventListener('click', () => {
      this.toggleMobileSidebar();
    });

    // Mobile overlay
    this.elements.overlay.addEventListener('click', () => {
      this.closeMobileSidebar();
    });

    // URL input
    this.elements.urlInput.addEventListener('keypress', (e) => {
      if (e.key === 'Enter') {
        this.handleScan();
      }
    });

    // Scan button
    this.elements.scanBtn.addEventListener('click', () => {
      this.handleScan();
    });

    // Upgrade button
    this.elements.upgradeBtn.addEventListener('click', () => {
      this.handleUpgrade();
    });

    // Populate capabilities
    this.renderCapabilities();

    // Populate quick actions
    this.renderQuickActions();
  }

  renderCapabilities() {
    const capabilities = [
      { id: 'xss', label: 'XSS Injection Detection' },
      { id: 'csrf', label: 'CSRF Token Validation' },
      { id: 'headers', label: 'Security Headers Check' },
      { id: 'sql', label: 'SQL Injection Testing' },
      { id: 'cors', label: 'CORS Misconfiguration' },
      { id: 'auth', label: 'Authentication Issues' },
    ];

    this.elements.capabilitiesList.innerHTML = capabilities
      .map(
        (cap) => `
          <li class="capability-item">
            <svg class="capability-icon" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"></polygon>
            </svg>
            <span class="capability-label">${cap.label}</span>
          </li>
        `
      )
      .join('');
  }

  renderQuickActions() {
    const actions = [
      { id: 'history', label: 'History' },
      { id: 'network', label: 'Network' },
      { id: 'infrastructure', label: 'Infrastructure' },
      { id: 'export', label: 'Export' },
    ];

    this.elements.quickActionsGrid.innerHTML = actions
      .map(
        (action) => `
          <button class="quick-action-button" data-action="${action.id}" aria-label="${action.label}">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              ${this.getIconSVGPath(action.id)}
            </svg>
            <span class="action-label">${action.label}</span>
          </button>
        `
      )
      .join('');

    // Attach quick action listeners
    document.querySelectorAll('.quick-action-button').forEach((btn) => {
      btn.addEventListener('click', (e) => {
        this.handleQuickAction(e.currentTarget.dataset.action);
      });
    });
  }

  getIconSVGPath(actionId) {
    const icons = {
      history:
        '<circle cx="12" cy="12" r="10"></circle><polyline points="12 6 12 12 16 14"></polyline>',
      network:
        '<circle cx="12" cy="12" r="1"></circle><circle cx="19" cy="12" r="1"></circle><circle cx="5" cy="12" r="1"></circle><line x1="12" y1="5" x2="12" y2="1"></line><line x1="12" y1="23" x2="12" y2="19"></line><line x1="4.22" y1="4.22" x2="1.46" y2="1.46"></line><line x1="19.07" y1="19.07" x2="21.83" y2="21.83"></line><line x1="1.46" y1="4.22" x2="4.22" y2="1.46"></line><line x1="19.07" y1="4.22" x2="21.83" y2="1.46"></line>',
      infrastructure:
        '<rect x="4" y="4" width="16" height="16" rx="2"></rect><rect x="9" y="9" width="6" height="6"></rect><path d="M9 4V2"></path><path d="M15 4V2"></path><path d="M9 20v2"></path><path d="M15 20v2"></path><path d="M20 9h2"></path><path d="M20 15h2"></path><path d="M4 9H2"></path><path d="M4 15H2"></path>',
      export:
        '<path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path><polyline points="7 10 12 15 17 10"></polyline><line x1="12" y1="15" x2="12" y2="3"></line>',
    };
    return icons[actionId] || '';
  }

  handleScan() {
    const url = this.elements.urlInput.value.trim();

    if (!url) {
      this.showMessage('Please enter a valid URL', 'error');
      return;
    }

    // Disable button and show loading state
    this.elements.scanBtn.disabled = true;
    this.elements.scanBtn.style.opacity = '0.6';
    this.elements.scanBtn.innerHTML += ' <span>Scanning...</span>';

    // Call provided callback
    this.options.onScan(url);

    // Reset button after 2 seconds (or adjust based on actual scan time)
    setTimeout(() => {
      this.elements.scanBtn.disabled = false;
      this.elements.scanBtn.style.opacity = '1';
      this.elements.scanBtn.textContent = ''; // Reset will fail, so manually reset
      this.elements.scanBtn.innerHTML =
        '<svg class="button-icon" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"></polygon></svg><span>SCAN</span>';
    }, 2000);

    // Clear input
    this.elements.urlInput.value = '';
  }

  handleQuickAction(actionId) {
    // Update active state
    document.querySelectorAll('.quick-action-button').forEach((btn) => {
      btn.classList.remove('active');
    });
    document.querySelector(`[data-action="${actionId}"]`).classList.add('active');

    this.state.activeSection = actionId;
    this.options.onNavigate(actionId);
    this.closeMobileSidebar();
  }

  handleUpgrade() {
    this.options.onUpgrade();
    this.closeMobileSidebar();
  }

  toggleMobileSidebar() {
    if (this.state.isMobileOpen) {
      this.closeMobileSidebar();
    } else {
      this.openMobileSidebar();
    }
  }

  openMobileSidebar() {
    this.state.isMobileOpen = true;
    this.elements.sidebar.classList.add('mobile-open');
    this.elements.overlay.style.display = 'block';
    this.elements.menuIcon.style.display = 'none';
    this.elements.closeIcon.style.display = 'block';
  }

  closeMobileSidebar() {
    this.state.isMobileOpen = false;
    this.elements.sidebar.classList.remove('mobile-open');
    this.elements.overlay.style.display = 'none';
    this.elements.menuIcon.style.display = 'block';
    this.elements.closeIcon.style.display = 'none';
  }

  showMessage(message, type = 'info') {
    // Simple message display - customize as needed
    console.log(`[${type.toUpperCase()}]: ${message}`);
    // You could create a toast notification here
  }

  // Public API methods

  setActiveSection(sectionId) {
    this.state.activeSection = sectionId;
    document.querySelectorAll('.quick-action-button').forEach((btn) => {
      btn.classList.toggle('active', btn.dataset.action === sectionId);
    });
  }

  getActiveSection() {
    return this.state.activeSection;
  }

  updateURL(url) {
    this.elements.urlInput.value = url;
  }

  getURLInput() {
    return this.elements.urlInput.value;
  }

  destroy() {
    document.querySelector('.sidebar-mobile-toggle')?.remove();
    document.querySelector('.security-sidebar')?.remove();
    document.querySelector('.sidebar-overlay')?.remove();
  }
}

// Export for use in modules
if (typeof module !== 'undefined' && module.exports) {
  module.exports = SecuritySidebar;
}
